import Head from "next/head";
import ClayNav from "@clayui/nav";
import ClayIcon from "@clayui/icon";

export default function Jobs() {
  return (
    <>
      <Head>
        <title>Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <ClayNav>
          <ClayNav.Item>
            <ClayNav.Link href="/">{"Dashboard"}</ClayNav.Link>
          </ClayNav.Item>
          <ClayNav.Item>
            <ClayNav.Link active href="/jobs">{"Jobs"}</ClayNav.Link>
          </ClayNav.Item>
          <ClayNav.Item>
            <ClayNav.Link href="/report">{"Report"}</ClayNav.Link>
          </ClayNav.Item>
        </ClayNav>
      </header>

      <main>
        <h1>Jobs</h1>
      </main>

      <footer>
        <span>Footer</span>
      </footer>
    </>
  );
}
